export  const AUTH_SUCCESS = "auth_success";
export  const ERROR_MSG = "error_msg";
export  const RETERROR = "ret_render";
export  const RESET_USER = "reset_user";
export  const RECEIV_EUSER = "receiv_euser";
export  const RECEIVE_USERLIST = "RECEIVE_USERLIST";
export  const USERLIST_ERR = "USERLIST_ERR";
export const RECEIVE_MSG_LIST = 'receive_msg_list' ;// 接收消息列表
export const RECEIVE_MSG = 'receive_msg'; // 接收一条消息
export const MSG_READ = 'msg_read'; // 标识消息已读